# 语言
language: node_js
# node版本
node_js:
  - 8
# 指定缓存模块
cache:
  directories:
    - node_modules
# 监听分支
branches:
  only:
    - master
install:
  - npm install
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "DealiAxy"
  - git config user.email "admin@deali.cn"
  - sed -i "s/{GH_TOKEN}/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy
# 通知
notifications:
  email:
    - admin@deali.cn
  on_success: change
  on_failure: always